# Generated by Django 4.1.7 on 2023-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user  with that email already exists.'}, max_length=254, verbose_name='email'),
        ),
    ]
