# Generated by Django 4.1.7 on 2023-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
